# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f649ee1c55249effcaae8cd9dc1e6d557c22f2a3abf6fe48d6fc493c390e01df528d852ebebf8398ce8aa74e339441e367e2b67d1030bff5ca10be652aa1ed

test:
  secret_key_base: b279d493916f4a3bbac4c0ec2fa37e880ed8d6ca62bade884c2116e27fe6319e8f2dbaa323c259379f1ba59818409d5e2bab9eb583aae6d73a1a90c1150a7588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
