User.create!([
  {email: "lewiszulauf@email.com", password_digest: "$2a$10$reiozyjnqNKnLt5rG5uhQuEs0dS5ITmVOTuE2gaDKAWe80GRyFlii", group_id: 1, first_name: "Lewis", last_name: "Zulauf", birthday: "1964-10-27 05:00:00", anniversary: "1984-01-14 05:00:00", admin: false},
  {email: "liziike@email.com", password_digest: "$2a$10$Esr6zRdug5QkwYP4kNAS9OsnXICsGP1gMxulhxK.GjDbaQ0FpPO1m", group_id: 1, first_name: "Lizi", last_name: "Ike", birthday: "1981-01-12 05:00:00", anniversary: nil, admin: false},
  {email: "dadike@email.com", password_digest: "$2a$10$Bcn1vrDMqfCljpBNyhczz.0BaoT0XOPI6oD5wo89gDrqL3slWJy9u", group_id: 1, first_name: "Dad", last_name: "Ike", birthday: "1950-02-10 05:00:00", anniversary: nil, admin: false},
  {email: "brice@email.com", password_digest: "$2a$10$NL4awxK16aLCYW5Uzngm/uxdJomdmw0LGB1/yfWVxv0HP0ecJxv0e", group_id: 7, first_name: "Brian", last_name: "Rice", birthday: "1981-01-01 05:00:00", anniversary: nil, admin: false},
  {email: "derrickike@email.com", password_digest: "$2a$10$PbtKQ/0aP35jYbWfALp1ueLHt0iwjDGDlE4Z0DYiZbXUuadbgfAkm", group_id: 1, first_name: "Derrick", last_name: "Ike", birthday: "1988-11-11 05:00:00", anniversary: nil, admin: false},
  {email: "myrtislind@email.com", password_digest: "$2a$10$DK760T/BhWTB/gWtf3eZ4eB3HqOmZKVzt5GOoEMpnnQ.i0XveZorW", group_id: 7, first_name: "Myrtis", last_name: "Lind", birthday: "1950-08-10 04:00:00", anniversary: "1983-03-06 05:00:00", admin: false},
  {email: "yvonneike@email.com", password_digest: "$2a$10$Roj2/ruAj2zvhbyiZgqKMOZP96RsQyMu0KPEoM2q6SNcFOgl19jwi", group_id: 1, first_name: "Yvonne", last_name: "Ike", birthday: "1981-11-25 10:00:00", anniversary: nil, admin: true},
  {email: "jakaylaschmitt@email.com", password_digest: "$2a$10$vxy57xosp.ZgsaY/Cc7zyOKdLzMHemqGOLAfBEutYU5s2IEAAbIle", group_id: 1, first_name: "Jakayla", last_name: "Schmitt", birthday: "1999-01-21 10:00:00", anniversary: nil, admin: false},
  {email: "lewiszulauf@email.com", password_digest: "$2a$10$reiozyjnqNKnLt5rG5uhQuEs0dS5ITmVOTuE2gaDKAWe80GRyFlii", group_id: 1, first_name: "Lewis", last_name: "Zulauf", birthday: "1964-10-27 05:00:00", anniversary: "1984-01-14 05:00:00", admin: false},
  {email: "liziike@email.com", password_digest: "$2a$10$Esr6zRdug5QkwYP4kNAS9OsnXICsGP1gMxulhxK.GjDbaQ0FpPO1m", group_id: 1, first_name: "Lizi", last_name: "Ike", birthday: "1981-01-12 05:00:00", anniversary: nil, admin: false},
  {email: "dadike@email.com", password_digest: "$2a$10$Bcn1vrDMqfCljpBNyhczz.0BaoT0XOPI6oD5wo89gDrqL3slWJy9u", group_id: 1, first_name: "Dad", last_name: "Ike", birthday: "1950-02-10 05:00:00", anniversary: nil, admin: false},
  {email: "brice@email.com", password_digest: "$2a$10$NL4awxK16aLCYW5Uzngm/uxdJomdmw0LGB1/yfWVxv0HP0ecJxv0e", group_id: 7, first_name: "Brian", last_name: "Rice", birthday: "1981-01-01 05:00:00", anniversary: nil, admin: false},
  {email: "derrickike@email.com", password_digest: "$2a$10$PbtKQ/0aP35jYbWfALp1ueLHt0iwjDGDlE4Z0DYiZbXUuadbgfAkm", group_id: 1, first_name: "Derrick", last_name: "Ike", birthday: "1988-11-11 05:00:00", anniversary: nil, admin: false},
  {email: "myrtislind@email.com", password_digest: "$2a$10$DK760T/BhWTB/gWtf3eZ4eB3HqOmZKVzt5GOoEMpnnQ.i0XveZorW", group_id: 7, first_name: "Myrtis", last_name: "Lind", birthday: "1950-08-10 04:00:00", anniversary: "1983-03-06 05:00:00", admin: false},
  {email: "yvonneike@email.com", password_digest: "$2a$10$Roj2/ruAj2zvhbyiZgqKMOZP96RsQyMu0KPEoM2q6SNcFOgl19jwi", group_id: 1, first_name: "Yvonne", last_name: "Ike", birthday: "1981-11-25 10:00:00", anniversary: nil, admin: true},
  {email: "jakaylaschmitt@email.com", password_digest: "$2a$10$vxy57xosp.ZgsaY/Cc7zyOKdLzMHemqGOLAfBEutYU5s2IEAAbIle", group_id: 1, first_name: "Jakayla", last_name: "Schmitt", birthday: "1999-01-21 10:00:00", anniversary: nil, admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Spongebob", last_name: "Ike", birthday: "1999-01-21 10:00:00", anniversary: nil, admin: false},
  {email: "mariejohnson@email.com", password_digest: "$2a$10$3zykervbMUgdJTGvkn0cKu4tCsGDdZeOL7Yw7otFm6dzRa9bA5lQa", group_id: 9, first_name: "Marie", last_name: "Johnson", birthday: nil, anniversary: nil, admin: false},
  {email: "momike@email.com", password_digest: "$2a$10$jIBka1IYpQfVCW33VgijG.XxblfHIuYAZhE5.w6yXXZFfzJcVk0oO", group_id: 1, first_name: "Mom", last_name: "Ike", birthday: "1955-08-29 04:00:00", anniversary: "1981-03-07 05:00:00", admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Sheila", last_name: "Odiwe", birthday: "1975-06-25 08:00:00", anniversary: nil, admin: false},
  {email: "myfamily@mailinator.com", password_digest: "$2a$10$88dgjox4c2fGD6hDJhdzLuB8XwXPxPC0qURv67QhfoL9gLYRUHq8K", group_id: 8, first_name: "Uchendu", last_name: "Nwachuku", birthday: nil, anniversary: nil, admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Jane", last_name: "Udoewa", birthday: "1981-05-20 08:00:00", anniversary: nil, admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Ify", last_name: "Ike", birthday: "1981-11-25 10:00:00", anniversary: nil, admin: false},
  {email: "lewiszulauf@email.com", password_digest: "$2a$10$reiozyjnqNKnLt5rG5uhQuEs0dS5ITmVOTuE2gaDKAWe80GRyFlii", group_id: 1, first_name: "Lewis", last_name: "Zulauf", birthday: "1964-10-27 05:00:00", anniversary: "1984-01-14 05:00:00", admin: false},
  {email: "liziike@email.com", password_digest: "$2a$10$Esr6zRdug5QkwYP4kNAS9OsnXICsGP1gMxulhxK.GjDbaQ0FpPO1m", group_id: 1, first_name: "Lizi", last_name: "Ike", birthday: "1981-01-12 05:00:00", anniversary: nil, admin: false},
  {email: "dadike@email.com", password_digest: "$2a$10$Bcn1vrDMqfCljpBNyhczz.0BaoT0XOPI6oD5wo89gDrqL3slWJy9u", group_id: 1, first_name: "Dad", last_name: "Ike", birthday: "1950-02-10 05:00:00", anniversary: nil, admin: false},
  {email: "brice@email.com", password_digest: "$2a$10$NL4awxK16aLCYW5Uzngm/uxdJomdmw0LGB1/yfWVxv0HP0ecJxv0e", group_id: 7, first_name: "Brian", last_name: "Rice", birthday: "1981-01-01 05:00:00", anniversary: nil, admin: false},
  {email: "derrickike@email.com", password_digest: "$2a$10$PbtKQ/0aP35jYbWfALp1ueLHt0iwjDGDlE4Z0DYiZbXUuadbgfAkm", group_id: 1, first_name: "Derrick", last_name: "Ike", birthday: "1988-11-11 05:00:00", anniversary: nil, admin: false},
  {email: "myrtislind@email.com", password_digest: "$2a$10$DK760T/BhWTB/gWtf3eZ4eB3HqOmZKVzt5GOoEMpnnQ.i0XveZorW", group_id: 7, first_name: "Myrtis", last_name: "Lind", birthday: "1950-08-10 04:00:00", anniversary: "1983-03-06 05:00:00", admin: false},
  {email: "yvonneike@email.com", password_digest: "$2a$10$Roj2/ruAj2zvhbyiZgqKMOZP96RsQyMu0KPEoM2q6SNcFOgl19jwi", group_id: 1, first_name: "Yvonne", last_name: "Ike", birthday: "1981-11-25 10:00:00", anniversary: nil, admin: true},
  {email: "jakaylaschmitt@email.com", password_digest: "$2a$10$vxy57xosp.ZgsaY/Cc7zyOKdLzMHemqGOLAfBEutYU5s2IEAAbIle", group_id: 1, first_name: "Jakayla", last_name: "Schmitt", birthday: "1999-01-21 10:00:00", anniversary: nil, admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Spongebob", last_name: "Ike", birthday: "1999-01-21 10:00:00", anniversary: nil, admin: false},
  {email: "mariejohnson@email.com", password_digest: "$2a$10$3zykervbMUgdJTGvkn0cKu4tCsGDdZeOL7Yw7otFm6dzRa9bA5lQa", group_id: 9, first_name: "Marie", last_name: "Johnson", birthday: nil, anniversary: nil, admin: false},
  {email: "momike@email.com", password_digest: "$2a$10$jIBka1IYpQfVCW33VgijG.XxblfHIuYAZhE5.w6yXXZFfzJcVk0oO", group_id: 1, first_name: "Mom", last_name: "Ike", birthday: "1955-08-29 04:00:00", anniversary: "1981-03-07 05:00:00", admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Sheila", last_name: "Odiwe", birthday: "1975-06-25 08:00:00", anniversary: nil, admin: false},
  {email: "myfamily@mailinator.com", password_digest: "$2a$10$88dgjox4c2fGD6hDJhdzLuB8XwXPxPC0qURv67QhfoL9gLYRUHq8K", group_id: 8, first_name: "Uchendu", last_name: "Nwachuku", birthday: nil, anniversary: nil, admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Jane", last_name: "Udoewa", birthday: "1981-05-20 08:00:00", anniversary: nil, admin: false},
  {email: nil, password_digest: nil, group_id: 1, first_name: "Ify", last_name: "Ike", birthday: "1981-11-25 10:00:00", anniversary: nil, admin: false}
])
RelativeType.create!([
  {name: "child", inverse_name: "parent"},
  {name: "grandparent", inverse_name: "grandchild"},
  {name: "aunt/uncle", inverse_name: "niece/nephew"},
  {name: "sibling", inverse_name: "sibling"},
  {name: "cousin", inverse_name: "cousin"},
  {name: "spouse", inverse_name: "spouse"},
  {name: "parent", inverse_name: "child"},
  {name: "niece/nephew", inverse_name: "aunt/uncle"},
  {name: "grandchild", inverse_name: "grandparent"},
  {name: "self", inverse_name: "self"},
  {name: "in-law", inverse_name: "in-law"}
])
Group.create!([
  {name: "Ike"},
  {name: "Smith"},
  {name: "Jones"},
  {name: "Williams"},
  {name: "Fox"},
  {name: "Sanchez"},
  {name: "Rice"},
  {name: "Nwachuku"},
  {name: "Johnson"}
])
Image.create!([
  {url: "https://robohash.org/recusandaesitvoluptas.png?size=300x300&set=set1", user_id: 1},
  {url: "https://robohash.org/estquaeratquae.png?size=300x300&set=set1", user_id: 2},
  {url: "https://robohash.org/velitnonassumenda.png?size=300x300&set=set1", user_id: 3},
  {url: "https://robohash.org/quiaautfacilis.png?size=300x300&set=set1", user_id: 4},
  {url: "https://robohash.org/dolorquidignissimos.png?size=300x300&set=set1", user_id: 5},
  {url: "https://robohash.org/impeditdoloremquedoloribus.png?size=300x300&set=set1", user_id: 6},
  {url: "https://robohash.org/essepossimusomnis.png?size=300x300&set=set1", user_id: 7},
  {url: "https://robohash.org/dolorinoptio.png?size=300x300&set=set1", user_id: 8},
  {url: "https://robohash.org/laudantiumvitaeadipisci.png?size=300x300&set=set1", user_id: 9},
  {url: "https://robohash.org/sunteumesse.png?size=300x300&set=set1", user_id: 10},
  {url: "https://robohash.org/impeditreprehenderitlabore.png?size=300x300&set=set1", user_id: 11},
  {url: "https://robohash.org/velitdoloribusdolor.png?size=300x300&set=set1", user_id: 12},
  {url: "https://robohash.org/nemoinperspiciatis.png?size=300x300&set=set1", user_id: 13},
  {url: "https://robohash.org/porrodolorumest.png?size=300x300&set=set1", user_id: 14},
  {url: "https://robohash.org/autcorporistempore.png?size=300x300&set=set1", user_id: 15},
  {url: "https://robohash.org/quiquiaaut.png?size=300x300&set=set1", user_id: 16},
  {url: "https://robohash.org/asperioresestsequi.png?size=300x300&set=set1", user_id: 17},
  {url: "https://robohash.org/blanditiisquodesse.png?size=300x300&set=set1", user_id: 18},
  {url: "https://robohash.org/etquidemenim.png?size=300x300&set=set1", user_id: 19},
  {url: "https://robohash.org/doloreetmolestiae.png?size=300x300&set=set1", user_id: 20},
  {url: "https://robohash.org/etmaioresiusto.png?size=300x300&set=set1", user_id: 21},
  {url: "https://robohash.org/etvoluptatevoluptatibus.png?size=300x300&set=set1", user_id: 22},
  {url: "https://robohash.org/temporibussapienteet.png?size=300x300&set=set1", user_id: 23},
  {url: "https://robohash.org/estducimusquae.png?size=300x300&set=set1", user_id: 24},
  {url: "https://robohash.org/dolorumharumaccusantium.png?size=300x300&set=set1", user_id: 25},
  {url: "https://robohash.org/doloreminventoremaxime.png?size=300x300&set=set1", user_id: 26},
  {url: "https://robohash.org/culpaenimincidunt.png?size=300x300&set=set1", user_id: 27},
  {url: "https://robohash.org/asperiorescorporisdoloribus.png?size=300x300&set=set1", user_id: 28},
  {url: "https://robohash.org/consequaturanimiquia.png?size=300x300&set=set1", user_id: 29},
  {url: "https://robohash.org/architectoeiussed.png?size=300x300&set=set1", user_id: 30},
  {url: "https://robohash.org/suntquiab.png?size=300x300&set=set1", user_id: 31},
  {url: "https://robohash.org/placeatculpalaboriosam.png?size=300x300&set=set1", user_id: 32},
  {url: "https://robohash.org/suntdolorconsequatur.png?size=300x300&set=set1", user_id: 33},
  {url: "https://robohash.org/molestiasdignissimosdolores.png?size=300x300&set=set1", user_id: 34},
  {url: "https://robohash.org/autsimiliqueet.png?size=300x300&set=set1", user_id: 35},
  {url: "https://robohash.org/nonimpediteveniet.png?size=300x300&set=set1", user_id: 36},
  {url: "https://robohash.org/consequunturetsapiente.png?size=300x300&set=set1", user_id: 37},
  {url: "https://robohash.org/etquiaiste.png?size=300x300&set=set1", user_id: 38},
  {url: "https://robohash.org/autilloplaceat.png?size=300x300&set=set1", user_id: 1},
  {url: "https://robohash.org/sequirepellatexplicabo.png?size=300x300&set=set1", user_id: 2},
  {url: "https://robohash.org/suntlaboriosamdoloribus.png?size=300x300&set=set1", user_id: 3},
  {url: "https://robohash.org/voluptasconsequunturodio.png?size=300x300&set=set1", user_id: 4},
  {url: "https://robohash.org/velitmagnamsoluta.png?size=300x300&set=set1", user_id: 5},
  {url: "https://robohash.org/quaeratautemeius.png?size=300x300&set=set1", user_id: 6},
  {url: "https://robohash.org/cupiditatesitsunt.png?size=300x300&set=set1", user_id: 7},
  {url: "https://robohash.org/quosetnulla.png?size=300x300&set=set1", user_id: 8},
  {url: "https://robohash.org/iustomolestiasmolestiae.png?size=300x300&set=set1", user_id: 9},
  {url: "https://robohash.org/utlaboriosamenim.png?size=300x300&set=set1", user_id: 10},
  {url: "https://robohash.org/quocumquequia.png?size=300x300&set=set1", user_id: 11},
  {url: "https://robohash.org/sintitaquealias.png?size=300x300&set=set1", user_id: 12},
  {url: "https://robohash.org/etpariaturin.png?size=300x300&set=set1", user_id: 13},
  {url: "https://robohash.org/possimusrationeipsum.png?size=300x300&set=set1", user_id: 14},
  {url: "https://robohash.org/ipsamaccusamuslibero.png?size=300x300&set=set1", user_id: 15},
  {url: "https://robohash.org/aliquamdoloresvoluptas.png?size=300x300&set=set1", user_id: 16},
  {url: "https://robohash.org/accusamusrerumet.png?size=300x300&set=set1", user_id: 17},
  {url: "https://robohash.org/sedameteius.png?size=300x300&set=set1", user_id: 18},
  {url: "https://robohash.org/quidemquinam.png?size=300x300&set=set1", user_id: 19},
  {url: "https://robohash.org/optioetdolores.png?size=300x300&set=set1", user_id: 20},
  {url: "https://robohash.org/explicaboetrepellendus.png?size=300x300&set=set1", user_id: 21},
  {url: "https://robohash.org/animiquisaccusamus.png?size=300x300&set=set1", user_id: 22},
  {url: "https://robohash.org/ipsumremquam.png?size=300x300&set=set1", user_id: 23},
  {url: "https://robohash.org/voluptatemquiaincidunt.png?size=300x300&set=set1", user_id: 24},
  {url: "https://robohash.org/etrepellendusvitae.png?size=300x300&set=set1", user_id: 25},
  {url: "https://robohash.org/veroutnon.png?size=300x300&set=set1", user_id: 26},
  {url: "https://robohash.org/autfacerequos.png?size=300x300&set=set1", user_id: 27},
  {url: "https://robohash.org/omnisrepellatsed.png?size=300x300&set=set1", user_id: 28},
  {url: "https://robohash.org/atquemolestiasqui.png?size=300x300&set=set1", user_id: 29},
  {url: "https://robohash.org/etillumab.png?size=300x300&set=set1", user_id: 30},
  {url: "https://robohash.org/sequivoluptasquia.png?size=300x300&set=set1", user_id: 31},
  {url: "https://robohash.org/ideteligendi.png?size=300x300&set=set1", user_id: 32},
  {url: "https://robohash.org/doloresdistinctiout.png?size=300x300&set=set1", user_id: 33},
  {url: "https://robohash.org/quasietquia.png?size=300x300&set=set1", user_id: 34},
  {url: "https://robohash.org/harumetqui.png?size=300x300&set=set1", user_id: 35},
  {url: "https://robohash.org/magnidebitisqui.png?size=300x300&set=set1", user_id: 36},
  {url: "https://robohash.org/etautlaboriosam.png?size=300x300&set=set1", user_id: 37},
  {url: "https://robohash.org/necessitatibusnemonostrum.png?size=300x300&set=set1", user_id: 38},
  {url: "https://robohash.org/maioresquisquia.png?size=300x300&set=set1", user_id: 1},
  {url: "https://robohash.org/molestiasutdolorem.png?size=300x300&set=set1", user_id: 2},
  {url: "https://robohash.org/reiciendisipsamquisquam.png?size=300x300&set=set1", user_id: 3},
  {url: "https://robohash.org/omnisidet.png?size=300x300&set=set1", user_id: 4},
  {url: "https://robohash.org/suscipitnamfacere.png?size=300x300&set=set1", user_id: 5},
  {url: "https://robohash.org/eaetet.png?size=300x300&set=set1", user_id: 6},
  {url: "https://robohash.org/consecteturestut.png?size=300x300&set=set1", user_id: 7},
  {url: "https://robohash.org/quasquosanimi.png?size=300x300&set=set1", user_id: 8},
  {url: "https://robohash.org/sedadipisciaut.png?size=300x300&set=set1", user_id: 9},
  {url: "https://robohash.org/possimusnihilbeatae.png?size=300x300&set=set1", user_id: 10},
  {url: "https://robohash.org/mollitiavelnatus.png?size=300x300&set=set1", user_id: 11},
  {url: "https://robohash.org/autminusperspiciatis.png?size=300x300&set=set1", user_id: 12},
  {url: "https://robohash.org/architectolaboriosamunde.png?size=300x300&set=set1", user_id: 13},
  {url: "https://robohash.org/omnismollitiaaliquam.png?size=300x300&set=set1", user_id: 14},
  {url: "https://robohash.org/adtemporibusalias.png?size=300x300&set=set1", user_id: 15},
  {url: "https://robohash.org/fugitquibusdamipsam.png?size=300x300&set=set1", user_id: 16},
  {url: "https://robohash.org/quiliberoin.png?size=300x300&set=set1", user_id: 17},
  {url: "https://robohash.org/iureipsamvoluptates.png?size=300x300&set=set1", user_id: 18},
  {url: "https://robohash.org/harumsolutaodit.png?size=300x300&set=set1", user_id: 19},
  {url: "https://robohash.org/quiadelectusipsam.png?size=300x300&set=set1", user_id: 20},
  {url: "https://robohash.org/iustositmodi.png?size=300x300&set=set1", user_id: 21},
  {url: "https://robohash.org/istefugaaccusamus.png?size=300x300&set=set1", user_id: 22},
  {url: "https://robohash.org/solutaerroret.png?size=300x300&set=set1", user_id: 23},
  {url: "https://robohash.org/ipsaetvoluptate.png?size=300x300&set=set1", user_id: 24},
  {url: "https://robohash.org/veritatismagniharum.png?size=300x300&set=set1", user_id: 25},
  {url: "https://robohash.org/quasmolestiaead.png?size=300x300&set=set1", user_id: 26},
  {url: "https://robohash.org/aliquiddoloremquedolorem.png?size=300x300&set=set1", user_id: 27},
  {url: "https://robohash.org/debitisestasperiores.png?size=300x300&set=set1", user_id: 28},
  {url: "https://robohash.org/quianostrumvoluptatem.png?size=300x300&set=set1", user_id: 29},
  {url: "https://robohash.org/sedquisenim.png?size=300x300&set=set1", user_id: 30},
  {url: "https://robohash.org/inetnesciunt.png?size=300x300&set=set1", user_id: 31},
  {url: "https://robohash.org/etrepellendusfacere.png?size=300x300&set=set1", user_id: 32},
  {url: "https://robohash.org/distinctioidtotam.png?size=300x300&set=set1", user_id: 33},
  {url: "https://robohash.org/illoexcepturifacere.png?size=300x300&set=set1", user_id: 34},
  {url: "https://robohash.org/maximesuscipitvero.png?size=300x300&set=set1", user_id: 35},
  {url: "https://robohash.org/quodlaboriosamarchitecto.png?size=300x300&set=set1", user_id: 36},
  {url: "https://robohash.org/debitisautembeatae.png?size=300x300&set=set1", user_id: 37},
  {url: "https://robohash.org/voluptasconsequaturassumenda.png?size=300x300&set=set1", user_id: 38},
  {url: "https://robohash.org/nonnumquammollitia.png?size=300x300&set=set1", user_id: 1},
  {url: "https://robohash.org/eosconsecteturesse.png?size=300x300&set=set1", user_id: 2},
  {url: "https://robohash.org/quidemmaioresqui.png?size=300x300&set=set1", user_id: 3},
  {url: "https://robohash.org/estimpeditdicta.png?size=300x300&set=set1", user_id: 4},
  {url: "https://robohash.org/nesciuntimpeditvoluptas.png?size=300x300&set=set1", user_id: 5},
  {url: "https://robohash.org/inametcorrupti.png?size=300x300&set=set1", user_id: 6},
  {url: "https://robohash.org/quamrepellatquae.png?size=300x300&set=set1", user_id: 7},
  {url: "https://robohash.org/velexpeditaofficia.png?size=300x300&set=set1", user_id: 8},
  {url: "https://robohash.org/sintutquaerat.png?size=300x300&set=set1", user_id: 9},
  {url: "https://robohash.org/maioresquasatque.png?size=300x300&set=set1", user_id: 10},
  {url: "https://robohash.org/magnamnequereprehenderit.png?size=300x300&set=set1", user_id: 11},
  {url: "https://robohash.org/pariaturdoloresvoluptatem.png?size=300x300&set=set1", user_id: 12},
  {url: "https://robohash.org/deseruntestet.png?size=300x300&set=set1", user_id: 13},
  {url: "https://robohash.org/veritatisquamquas.png?size=300x300&set=set1", user_id: 14},
  {url: "https://robohash.org/quiexcepturicumque.png?size=300x300&set=set1", user_id: 15},
  {url: "https://robohash.org/aperiamquiaquasi.png?size=300x300&set=set1", user_id: 16},
  {url: "https://robohash.org/voluptatesquiqui.png?size=300x300&set=set1", user_id: 17},
  {url: "https://robohash.org/eaautemofficia.png?size=300x300&set=set1", user_id: 18},
  {url: "https://robohash.org/voluptateistedistinctio.png?size=300x300&set=set1", user_id: 19},
  {url: "https://robohash.org/distinctioveniamaut.png?size=300x300&set=set1", user_id: 20},
  {url: "https://robohash.org/sitnobiset.png?size=300x300&set=set1", user_id: 21},
  {url: "https://robohash.org/ipsaiustopariatur.png?size=300x300&set=set1", user_id: 22},
  {url: "https://robohash.org/sintquodarchitecto.png?size=300x300&set=set1", user_id: 23},
  {url: "https://robohash.org/cupiditaterecusandaeautem.png?size=300x300&set=set1", user_id: 24},
  {url: "https://robohash.org/nonestab.png?size=300x300&set=set1", user_id: 25},
  {url: "https://robohash.org/itaqueconsequunturaut.png?size=300x300&set=set1", user_id: 26},
  {url: "https://robohash.org/estquonemo.png?size=300x300&set=set1", user_id: 27},
  {url: "https://robohash.org/delenitiquismagnam.png?size=300x300&set=set1", user_id: 28},
  {url: "https://robohash.org/consequaturetvero.png?size=300x300&set=set1", user_id: 29},
  {url: "https://robohash.org/dolorutnulla.png?size=300x300&set=set1", user_id: 30},
  {url: "https://robohash.org/expeditaetdistinctio.png?size=300x300&set=set1", user_id: 31},
  {url: "https://robohash.org/voluptatemrepellatautem.png?size=300x300&set=set1", user_id: 32},
  {url: "https://robohash.org/consecteturharumet.png?size=300x300&set=set1", user_id: 33},
  {url: "https://robohash.org/voluptatemreiciendiseos.png?size=300x300&set=set1", user_id: 34},
  {url: "https://robohash.org/istevoluptatumquis.png?size=300x300&set=set1", user_id: 35},
  {url: "https://robohash.org/sitmolestiaererum.png?size=300x300&set=set1", user_id: 36},
  {url: "https://robohash.org/consequunturfugiatvitae.png?size=300x300&set=set1", user_id: 37},
  {url: "https://robohash.org/repellendusdoloremqueaut.png?size=300x300&set=set1", user_id: 38}
])
Map.create!([
  {location: "bahamas", user_id: 7, latitude: 25.03428, longitude: -77.39628, description: "<a href='/familymembers/7'>Yvonne</a> is on vacation", group_id: 1}
])
Relationship.create!([
  {user_id: 7, relative_id: 5, relative_type_id: 4, group_id: 1},
  {user_id: 7, relative_id: 17, relative_type_id: 6, group_id: 1},
  {user_id: 7, relative_id: 15, relative_type_id: 10, group_id: 1}
])

StatusUpdate.create!([
  {post: "Tumblr art party tacos locavore direct trade church-key park.", user_id: 1, url: "https://robohash.org/etaspernaturnon.png?size=300x300&set=set1"},
  {post: "Pickled food truck neutra shoreditch pour-over mustache.", user_id: 2, url: "https://robohash.org/ullamquosdoloremque.png?size=300x300&set=set1"},
  {post: "Butcher readymade meggings disrupt quinoa bespoke leggings banh mi blue bottle.", user_id: 6, url: "https://robohash.org/utsitet.png?size=300x300&set=set1"}
])
